"""
Training routines for L2-robust classifiers.

Provides three training modes:
    - Standard: clean cross-entropy training, used as a baseline.
    - Gaussian: noise-augmented training for randomized smoothing (Cohen et al., 2019).
    - Adversarial: PGD-L2 or EOT-PGD adversarial training for empirical robustness.

Typical usage:
    train_standard(config, model, loader, device)
    train_gaussian(config, model, loader, device)
    train_adversarial(config, model, loader, device)
"""

from typing import Any

import torch
import torch.nn.functional as F
from torch import Tensor
from torch.nn import Module
from torch.utils.data import DataLoader
from tqdm import tqdm

from attacks import EOTPGDL2, L2PGDAttack


def _optim(cfg: Any, model: Module) -> torch.optim.Adam:
    return torch.optim.Adam(model.parameters(), lr=cfg.lr)


def _attack_kwargs(config: Any, train_attack_config: Any | None) -> dict[str, Any]:
    if train_attack_config is not None:
        if hasattr(train_attack_config, "items"):
            return dict(train_attack_config)
        return vars(train_attack_config)

    return {
        "epsilon": config.train_epsilon,
        "k": config.train_attack_steps,
        "a": config.train_step_size,
        "random_start": True,
        "loss_func": "xent",
    }


def train_adversarial(
    config: Any,
    model: Module,
    loader: DataLoader,
    device: torch.device,
    train_attack_config: Any | None = None,
) -> None:
    """
    Train model with adversarial examples generated by an L2 attack.

    Supports two attack modes controlled by config.adv_attack:
        - "pgd_l2": Standard PGD attack in L2 norm.
        - "eot": EOT PGD attack accounting for Gaussian noise (for smoothed classifiers).

    If train_attack_config is provided it overrides the attack parameters
    from config. Otherwise epsilon, step size, and number of steps are
    read from config.

    Args:
        config: Training config (see run_results.py)
        model: The classifier to train.
        loader: DataLoader providing (input, label) batches.
        device: Device to run training on.
        train_attack_config: Optional override for attack parameters. Accepts
                             a dict-like object or a namespace.
    """

    optimizer = _optim(config, model)
    attack_kwargs = _attack_kwargs(config, train_attack_config)

    if config.adv_attack == "pgd_l2":
        print("\n===== PGD L2 Attack======")
        attack = L2PGDAttack(model, **attack_kwargs)

    elif config.adv_attack == "eot":
        print("\n===== EOT PGD L2 Attack======")
        attack = EOTPGDL2(
            model, sigma=config.sigma, m=config.eot_samples, **attack_kwargs
        )

    for epoch in range(config.epochs):
        model.train()
        total_loss = 0.0
        total = 0

        for x, y in tqdm(loader, desc=f"l2 defense train {epoch + 1}/{config.epochs}"):
            x, y = x.to(device), y.to(device)
            x_adv = attack.perturb(x, y) #Apply attack to perturb inputs (EOT or regular PGD-L2)

            model.train()
            optimizer.zero_grad(set_to_none=True)
            loss = F.cross_entropy(model(x_adv), y)
            loss.backward()
            optimizer.step()

            total_loss += loss.item() * y.numel()
            total += y.numel()
        print(
            f"[l2_defense] epoch={epoch + 1}/{config.epochs} loss={total_loss / total:.4f}"
        )


def train_standard(
    config: Any,
    model: Module,
    loader: DataLoader,
    device: torch.device,
) -> None:
    """
    Train the base classifier with no defensive mechanisms.

    Args:
        config: Training config with attributes epochs and lr.
        model: The classifier to train.
        loader: DataLoader providing (input, label) batches.
        device: Device to run training on.
    """

    optimizer = _optim(config, model)
    model.train()

    for epoch in range(config.epochs):
        for x, y in loader:
            x, y = x.to(device), y.to(device)
            optimizer.zero_grad()

            loss = F.cross_entropy(model(x), y)
            loss.backward()
            optimizer.step()

        print(f"[standard] Epoch: {epoch+1}/{config.epochs}| Loss: {loss.item():.3f}")


def train_gaussian(
    config: Any,
    model: Module,
    loader: DataLoader,
    device: torch.device,
) -> None:
    """
    Train the base classifier under Gaussian noise augmentation.

    At each step, adds Gaussian noise with standard deviation config.sigma
    to the input before computing the loss.
    Training procedure for randomized smoothing (Cohen et al., 2019).

    Args:
        config: Training config with attributes epochs, lr, and sigma.
        model: The classifier to train.
        loader: DataLoader providing (input, label) batches.
        device: Device to run training on.
    """

    optimizer = _optim(config, model)
    model.train()

    for epoch in range(config.epochs):
        for x, y in loader:
            x, y = x.to(device), y.to(device)
    
            x_noisy = (x + torch.randn_like(x) * config.sigma).clamp(0, 1) # Applies pertubation to the input
            #Clamps down to [0,1] range to follow pixel value distribution (0-1)
            optimizer.zero_grad()

            loss = F.cross_entropy(model(x_noisy), y)
            loss.backward()
            optimizer.step()

        print(
            f"[rand_smooth] Epoch: {epoch+1}/{config.epochs}| Loss: {loss.item():.3f}"
        )
